* Kotlin cheat sheet for white board problem solving

** How to execute Kotlin code

#+begin_src java
kotlinc KotlinFileName.kt -include-runtime -d output.jar
java -jar output.jar
#+end_src

** Loop

#+begin_src java
for (item in collection) { print(item) }
for (i in 1..5) print(i) = 12345
for (i in 5..1) print(i) = 
for (i in 5 downTo 1) print(i) = 54321
for (i in 1..4 step 2) print(i) = 135
for (i in 4 downTo 1 step 2) print(i) = 531
for (index in collection.indices) { println("index = $index, element = ${collection[index]}") }
for ((index, element) in collection.withIndex()) { println("index = $index, element = $element") }
collection.forEach { element -> println(element) }
collection.forEachIndexed{index, element -> println("index = $index, element = $element") }
#+end_src

** Main Method

#+begin_src java
fun main(args: Array<String>) {
    // body
}

fun main() {
    // body
}
#+end_src

** String

*** String can be treated as a collection

#+begin_src java
val text = "kotlin"
for (letter in text) { println(letter) }
for (item in text.indices) { println(text[item]) }
#+end_src

*** Length

#+begin_src java
text.length
#+end_src

** Print collection

#+begin_src java
collection.joinToString()
collection.joinToString(separator = "DILIMITER")
#+end_src

** Basic Types

#+begin_src java
val a: Int = 10000
val d: Double = 100.00
val f: Float = 100.00f
val l: Long = 1000000004
val l = 1L
val letter: Char = 'A' 
val b: Boolean = true
val s: String = "hello"
#+end_src

** IntArray

 - Arrays of primitive types without boxing overhead
 - no inheritance relation to the Array class but same set of methods and properties

#+begin_src java
val x: IntArray = intArrayOf(1, 2, 3)
val arr = IntArray(5) // [0, 0, 0, 0, 0]
val arr = IntArray(5) { 42 } // [42, 42, 42, 42, 42]
var arr = IntArray(5) { it * 1 } // [0, 1, 2, 3, 4]

x.size // size property
arr[index] = value
#+end_src

* Notes

 - Arrays (Array<T>) in Kotlin has a fixed size. It can't be resized after initialization.
 - Collection which includes list, set, and map are resizeable.
 - IntArray stores primitive and unboxed items. Array<Int> and collection stores boxed types.

* To-the-power-of operator

** Manual

#+begin_src java
fun pow(base: Int, exponent: Int): Long {
    var result: Long = 1

    while (exponent != 0) {
        result *= base.toLong()
        --exponent
    }

    return result
}
#+end_src

** pow() from Math class

#+begin_src java
Math.pow(base.toDouble(), exponent.toDouble())
#+end_src

* Pre and post increment

#+begin_src java
++a increments and then returns the variable
a++ returns and then increments the variable
var a = 1
println(a++); //You will see 1
//Now a is 2
println(++a); //You will see 3
#+end_src

* Structural Jump Expressions (return, break, and continue)

 - return
   - returns from the nearest enclosing function or anonymous function
 - break
   - terminates the nearest enclosing loop
 - continue
   - skip remaining and continue with next step or proceeds to the next step of the nearest enclosing loop
